application/FlightBooking/FlightBooking/Controllers/BookingsController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace FlightBooking.Controllers
{
    public class BookingsController : Controller
    {
        private static readonly SqlParser Parser = new SqlParser();
        private static readonly SqlClient Client = new SqlClient(Parser);

        public ActionResult Index()
        {
            var email = CurrentUser.Email;
            if (string.IsNullOrWhiteSpace(email))
                return RedirectToAction("Login", "Account");

            var bookings = Client.GetBooking(email);
            return View("Index", bookings);
        }
        
        public ActionResult Book()
        {
            return View();
        }

        public ActionResult Cancel(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            var booking = Client.GetBooking(id.Value);
            if (booking == null)
            {
                return HttpNotFound();
            }

            return View(booking.BookingFlights);
        }

        [HttpPost, ActionName("Cancel")]
        [ValidateAntiForgeryToken]
        public ActionResult CancelConfirmed(int id)
        {
            Client.DeleteBooking(id);
            return RedirectToAction("Index");
        }
    }
}

application/FlightBooking/FlightBooking/Controllers/FlightSearchController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using FlightBooking.ViewModels;

namespace FlightBooking.Controllers
{
    public class FlightSearchController : Controller
    {
        private static readonly SqlParser Parser = new SqlParser();
        private static readonly SqlClient Client = new SqlClient(Parser);

        // GET: FlightSearch
        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search([Bind(Include = "DepartureAirport,ArrivalAirport,DepartureDate,ReturnDate,MaximumConnections,MaximumTime,MaximumPrice")] FlightSearchViewModel vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var connections = Client.GetRoutes(vm.DepartureDate, vm.DepartureAirport, vm.ArrivalAirport,
                        vm.MaximumConnections, vm.MaximumTime, vm.MaximumPrice);

                    var bookings = connections.Select(c => new FlightConnectionViewModel(c));
                    return View("Results", bookings);
                }
            }
            catch (Exception /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.)
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }

            return View(vm);
        }
    }
}

application/FlightBooking/FlightBooking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Flight Booking", "Search", "FlightSearch", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Search", "Search", "FlightSearch")</li>
                    <li>@Html.ActionLink("My Bookings", "Index", "Bookings")</li>
                    <li>@Html.ActionLink("My Account", "Index", "Account")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>